pybo/views/auth_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, flash, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from pybo import db
from pybo.form import UserCreateForm, UserLoginForm
from pybo.models import Question, User

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET','POST'))
def signup():
    form = UserCreateForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')

    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET','POST'))
def login():
    form = UserLoginForm()

    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = '존재하지 않는 사용자입니다.'
        elif not check_password_hash(user.password, form.password.data):
            error = '비밀번호가 올바르지 않습니다.'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))

        flash(error)

    return render_template('auth/login.html', form=form)

@bp.before_app_request   # 라우트 함수보다 선행해서 실행됨
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

pybo/views/chat_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect
from pybo import db
from pybo.form import QuestionForm, AnswerForm, HelpForm
from pybo.models import Question
from pybo.views.dialogflowapi import chat

bp = Blueprint('chat', __name__, url_prefix='/chat')


@bp.route('/bot/')
def Bot():
    return render_template('chat/chatbot.html')

@bp.route('/help/', methods=('GET','POST'))
def Help():
    form = HelpForm()
    if request.method == "POST" and form.validate_on_submit():
        result = chat(form.search.data,'1234')
        print(result)
        if result == '영화 순위 메뉴':
            return redirect(url_for('movierank.Movierank'))
        elif result == 'Go google':
            return redirect('http://www.google.com', code=302)


    return render_template('chat/help.html', form=form)

@bp.route('/chatvote/')
def chatVote():
    return render_template('chat/chatvote.html')

pybo/views/movie_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, flash, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from pybo import db
from pybo.form import NaverMovieForm
from pybo.models import Question, User
from pybo.views.movieapi import Mrank, navermovie

bp = Blueprint('movierank', __name__, url_prefix='/movie')

@bp.route('/rank/')
def Movierank():
    rankdata = Mrank()
    # print(rankdata)

    return render_template('movie/movierank.html', rankdata=rankdata)

@bp.route('/msearch/', methods=('GET','POST'))
def Navermovie():
    form = NaverMovieForm()

    if request.method == "POST" and form.validate_on_submit():
        print(form.moviesearch.data)
        result = navermovie(form.moviesearch.data)

        return render_template('movie/navermovie.html', movieinfo_list=result['items'], form=form)

    return render_template('movie/navermovie.html', form=form)

# redirect(url_for('naver.book', question_id=question_id))

pybo/views/naver_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, flash, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from pybo import db
from pybo.form import NaverBookForm
from pybo.models import Question, User
from pybo.views.naverapi import naverbook

bp = Blueprint('naver', __name__, url_prefix='/naver')

@bp.route('/book/', methods=('GET','POST'))  # 책 페이지 접근
def Naverbook():
    form = NaverBookForm()

    if request.method == "POST" and form.validate_on_submit():
        print(form.search.data)
        result = naverbook(form.search.data)

        return render_template('naver/naverbook.html', bookinfo_list=result['items'], form=form)

    return render_template('naver/naverbook.html', form=form)

# redirect(url_for('naver.book', question_id=question_id))

pybo/templates/base.html
<!-- base를 구축함으로써 스타일시트의 유지보수 측면을 유용하게 설계한다 -->
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">

    <a class="navbar-brand" href="{{ url_for('main.index') }}">
        <img src="{{ url_for('static', filename='logo100.png') }}" alt=""  width="30" height="30" class="d-inline-block align-text-top"> O N I X
    </a>

    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">

    {% if g.user %}
    <ul class="navbar-nav">
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }}님 로그아웃</a>
        </li>
    </ul>
    {% else %}
    <ul class="navbar-nav">
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('naver.Naverbook') }}">네이버책</a>
        </li>
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('movierank.Movierank') }}">영화순위</a>
        </li>
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('movierank.Navermovie') }}">영화검색</a>
        </li>
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('chat.Bot') }}">챗봇</a>
        </li>
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('chat.chatVote') }}">투표챗봇</a>
        </li>
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('chat.Help') }}">HELP</a>
        </li>
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
        </li>
        <li class="navbar-nav">
            <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
        </li>
    </ul>
    {% endif %}
    </div>
</nav>

<script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
<df-messenger
  intent="WELCOME"
  chat-title="TrotVote"
  agent-id="74ec0efc-426f-48ea-bfe9-89a8ed1869e0"
  language-code="ko"
></df-messenger>

{% block content %}
{% endblock %}

<script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>

</body>
</html>